### ISSUE TITLE
fatal error: ESPHelper32.h: No such file or directory

### ISSUE THREAD

**Issue by SteveRMann** [ItKindaWorks/ESPHelper32#3]
I put the folder: ESPHelper32-master in my Arduino\libraries\folder, and restarted the IDE.  What have I forgotten to do to use ESPHelper32 on a NodeMCU?

**Comment by per1234** [comment]
You must not have installed the library correctly. Try this:
1. Download https://github.com/ItKindaWorks/ESPHelper32/archive/master.zip
1. (In the Arduino IDE) Sketch > Include Library > Add .ZIP Library...
1. Select the downloaded .zip file.
1. Click "Open".

That should correctly install the library, after which you will not get the `ESPHelper32.h: No such file or directory` error anymore (you might still get other errors).

**Comment by ItKindaWorks** [comment]
Assuming this has been resolved. Closing.
