### ISSUE TITLE
WiFi.macAddress(mac) is called before mac address is vailable

### ISSUE THREAD

**Issue by NickJB** [ItKindaWorks/ESPHelper32#4]
bool ESPHelper32::begin(){
	if(_ssidSet){
		// Generate client name based on MAC address and last 8 bits of microsecond counter
		_clientName += "esp32-";
		uint8_t mac[6];
		// WiFi.macAddress(mac);
// 		_clientName += macToStr(mac);

		//set the wifi mode to station and begin the wifi (connect using either ssid or ssid/pass)
		WiFi.mode(WIFI_STA);
		if(_passSet){WiFi.begin(_currentNet.ssid, _currentNet.pass);}
		else{WiFi.begin(_currentNet.ssid);}

		WiFi.macAddress(mac);
		_clientName += macToStr(mac);

**Comment by ItKindaWorks** [comment]
This should be fixed. ESP8266 didnt care whether wifi.begin had been called but I guess ESP32 does care so I switched them around. Let me know if it still doesnt work after the swap.
